version: '3.1'
services:
  nginx:
    image: nginx
    volumes:
      - .dockerconfig/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - php
      - mariadb
    ports:
      - 8000:80
    networks:
      - frontend

  php:
    build: .dockerconfig/php
    volumes:
      - .dockerconfig/php/conf.d:/user/local/etc/php/conf.d
      - .:/var/www/html
    expose:
      - 9000
    networks:
      - frontend
      - backend

  redis:
    image: redis
    expose:
      - 6739
    networks:
      - frontend

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE_FILE: /run/secrets/db_database
      MYSQL_USER_FILE: /run/secrets/db_root_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    expose:
      - 3306
    secrets:
      - db_root_password
      - db_database
      - db_user
      - db_password
    networks:
      - backend

secrets:
  db_root_password:
    file: .dockerconfig/secrets/db-root-password
  db_database:
    file: .dockerconfig/secrets/db-database
  db_user:
    file: .dockerconfig/secrets/db-user
  db_password:
    file: .dockerconfig/secrets/db-password

networks:
  frontend:
  backend:
